ngrok:
  image: mrsix/my-ngrok
  ports:
    - "4441:4441"
    - "4442:4442"
    - "4443:4443"
    - "4444:4444"
    - "4445:4445"
    - "4446:4446"
    - "4447:4447"
    - "4448:4448"
    - "4449:4449"

redis_server:
  image: redis
  ports:
    - "6379:6379"
  volumes:
    - /usr/local/mydocker/redis/redis.conf:/usr/local/etc/redis/redis.conf
  command: redis-server /usr/local/etc/redis/redis.conf

mysql_server:
  image: mysql
  ports:
    - "3306:3306"
  volumes:
    - /usr/local/mydocker/mysql/cof:/etc/mysql/conf.d
    - /usr/local/mydocker/mysql/database:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root

wx_nbs:
  image: mrsix/wx-nbs
  links:
    - redis_server
    - mysql_server

nginx:
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - ngrok
    - wx_nbs
  volumes:
    - /usr/local/mydocker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - /usr/www/:/usr/www/
